[package]
name = "evm-deployment-info"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
libc = "0.2.168"
prettytable = "0.10.0"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde_json = "1.0.133"
